# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Newsletter
version:      0.03
version_from: lib/Newsletter.pm
installdirs:  site
requires:
    MIME::Explode:                 0.38
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
