# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Newsletter
version:      0.032
version_from: lib/Newsletter.pm
installdirs:  site
requires:
    File::Path:                    1.06
    File::Type:                    0.22
    MIME::Explode:                 0.38
    MIME::Lite:                    3.0
    Test::More:                    0
    Time::HiRes:                   1.65

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
